#!/bin/bash

# Place this menu in your path or make an alias to it.
# Change this to your Directory where the .menu scripts are kept
location=""${HOME}"/YouTubeVids/"

# Setup Text Colors
black=$(tput setaf 16)
white=$(tput setaf 15)
gray=$(tput setaf 236)
blue=$(tput setaf 21)
green=$(tput setaf 28)
red=$(tput setaf 1)
cyan=$(tput setaf 36)
purple=$(tput setaf 128)
brown=$(tput setaf 130)
yellow=$(tput setaf 214) # 226
orange=$(tput setaf 202)
pink=$(tput setaf 207)
lgray=$(tput setaf 241)
lblue=$(tput setaf 39)
lgreen=$(tput setaf 118)
lred=$(tput setaf 9)
lcyan=$(tput setaf 14)
lpurple=$(tput setaf 99)

blgray=$(tput setab 246) # Background Light Gray

BoGreen=$(tput bold; tput setaf 28) # Bold Green
ReverseGR=$(tput setaf 28; tput rev) 	# Reverse Green

invis=$(tput civis)			# Invisible Cursor
norm=$(tput cnorm)			# Normal Cursor
standout=$(tput smso)
blink=$(tput blink)
reverse=$(tput rev)
bold=$(tput bold) 
reset=$(tput sgr0)      #  Reset text attributes to normal

###############################################################

tput clear

mapfile -O 1 -t < <(for i in "${location}"*.menu; do printf "%b\n" $(basename -s .menu $i); done) titles

printf "%b\n\n"
#printf "%b\n" "${pink}""You Tube Channels\n\n"
printf "%b\n" "${pink}"
cat << 'EOF'
 __   __            _____      _             ____ _                            _     
 \ \ / /__  _   _  |_   _|   _| |__   ___   / ___| |__   __ _ _ __  _ __   ___| |___ 
  \ V / _ \| | | |   | || | | | '_ \ / _ \ | |   | '_ \ / _` | '_ \| '_ \ / _ \ / __|
   | | (_) | |_| |   | || |_| | |_) |  __/ | |___| | | | (_| | | | | | | |  __/ \__ \
   |_|\___/ \__,_|   |_| \__,_|_.__/ \___|  \____|_| |_|\__,_|_| |_|_| |_|\___|_|___/
                                                                                     
EOF
printf "%b\n" "${reset}"
i=1
until [ $i -gt ${#titles[@]} ]
do
	printf "${yellow} $i. \t${cyan}${titles[i]}${reset}\n"
	i=$(( i+1 ))
done

printf "%b\n" "${green}""  Single Digit Entries Require Enter Key to Be Pressed.
(Double Tap ESC to Exit or CTRL-C)"

# Get the users selection.
read -r -n 2 choice
tput el1; tput cuu 2; tput ed

# Assign the variable from the users choice.
if [[ ${choice} == $'\e'$'\e' ]]; then
tput cub 100;tput ed
exit
elif [ "${choice}" -ge 1 ] && [ "${choice}" -le ${#titles[@]} ]; then
selection="${titles[$choice]}"
fi
"${location}""${selection}".menu
tput clear
"$0"
